[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
size = 16.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

